//! VGCH Phase 1b Hypothesis 1 — cross-check pwdft-rs KB projector form
//! factors β_l(q) against an independent Python reference for every
//! heavy-atom pseudopotential in the VGCH scope.
//!
//! This extends the Si-only `vgcmp_beta_q_cross_check` (VGCMP Phase 2,
//! already green at 3e-12 Bohr^{3/2}) to the full VGCH residual set
//! (C, Fe, Cu, Ga, As, Na, Cl, Mg, O) plus Si/Al as guardrails. The
//! hypothesis under test: does pwdft-rs' Bessel transform disagree
//! with QE's `qe-7.5/upflib/beta_mod.f90:113` on *any* projector at
//! *any* q in the production range?
//!
//! - If C diamond (light, no semicore) matches AND Cu/Fe (semicore)
//!   match, the "different converged density" residual is NOT a β_l(q)
//!   form-factor bug. Hypothesis 1 is eliminated → move to H2 (SAD).
//! - If any element fails, we have a smoking gun for the residual.
//!
//! Tolerance: 1e-8 Bohr^{3/2} absolute. QE's printed `tab_beta` keeps
//! 8 digits; this tolerance pins us to the printable-precision floor.
//!
//! The Python reference is regenerated by
//! `scripts/validate/vgch_beta_l_heavy.py` into
//! `scripts/validate/vgch_beta_l_heavy.csv`. Both scripts use the
//! byte-identical Simpson quadrature (`qe-7.5/upflib/simpsn.f90` ↔
//! `src/numerics.rs::simpson_integrate` ↔ `simpson_qe` in the Python
//! reference), so the only thing being tested here is the radial
//! integrand assembly and unit-conversion bookkeeping.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    reason = "ERR2 § Phase 0: integration tests are allowed to panic"
)]

use std::fs;
use std::path::PathBuf;

use pwdft_rs::{
    consts::BOHR_TO_ANG,
    numerics::simpson_integrate,
    pseudopotential::{PseudopotentialData, load},
};

const CSV_REL_PATH: &str = "scripts/validate/vgch_beta_l_heavy.csv";

/// Per-row tolerance in Bohr^{3/2}. Si VGCMP Phase 2 agreed to 3e-12 on a
/// lighter (4-projector, no semicore) PP; the heavy semicore PPs have
/// larger form factors (|F| ≈ 10 Bohr^{3/2}) and sharper radial
/// structure, so we relax to 1e-8 — still 8 digits, matching QE's
/// printed `tab_beta` precision.
const TOL_BOHR_3_HALVES: f64 = 1.0e-8;

struct RefRow {
    element: String,
    projector_index: usize,
    l: i32,
    q_bohr_inv: f64,
    q_per_ang: f64,
    f_bohr_3halves: f64,
    f_ang_3halves: f64,
}

fn load_reference_csv(path: &PathBuf) -> Option<Vec<RefRow>> {
    let content = fs::read_to_string(path).ok()?;
    let mut rows = Vec::new();
    for (line_no, line) in content.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line_no == 0 {
            continue;
        }
        let fields: Vec<&str> = line.split(',').collect();
        assert!(
            fields.len() == 7,
            "malformed CSV row at line {}: {line:?} ({} fields)",
            line_no + 1,
            fields.len()
        );
        rows.push(RefRow {
            element: fields[0].trim().to_string(),
            projector_index: fields[1].trim().parse().unwrap(),
            l: fields[2].trim().parse().unwrap(),
            q_bohr_inv: fields[3].trim().parse().unwrap(),
            q_per_ang: fields[4].trim().parse().unwrap(),
            f_bohr_3halves: fields[5].trim().parse().unwrap(),
            f_ang_3halves: fields[6].trim().parse().unwrap(),
        });
    }
    Some(rows)
}

fn load_pp(element: &str) -> PseudopotentialData {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join(format!("pseudopotentials/nc/lda/{element}.upf"));
    load(&path).unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
}

/// Transcription of `src/potential/nonlocal.rs::spherical_bessel_j`.
fn spherical_bessel_j(l: i32, x: f64) -> f64 {
    assert!(l >= 0);
    if x.abs() < 1e-10 {
        return if l == 0 { 1.0 } else { 0.0 };
    }
    if l == 0 {
        return x.sin() / x;
    }
    if l == 1 {
        return x.sin() / (x * x) - x.cos() / x;
    }
    let mut jlm1 = x.sin() / x;
    let mut jl = x.sin() / (x * x) - x.cos() / x;
    for n in 1..l {
        let jlp1 = f64::from(2 * n + 1) / x * jl - jlm1;
        jlm1 = jl;
        jl = jlp1;
    }
    jl
}

/// Transcription of `src/potential/nonlocal.rs::bessel_transform_projector`.
///
/// `r_grid`, `rab` in Å; `chi = r·β(r)` in Å^{-1/2}; `q_ang_inv` in 1/Å.
/// Returns F_l(q) in Å^{3/2}.
fn f_l_of_q_rust(
    r_grid: &[f64],
    rab: &[f64],
    chi: &[f64],
    l: i32,
    q_ang_inv: f64,
) -> f64 {
    use std::f64::consts::PI;
    let n = r_grid.len();
    let mut integrand = vec![0.0_f64; n];
    for i in 0..n {
        let r = r_grid[i];
        let jl = spherical_bessel_j(l, q_ang_inv * r);
        integrand[i] = chi[i] * jl * r;
    }
    4.0 * PI * simpson_integrate(&integrand, rab)
}

#[test]
fn vgch_h1_beta_l_matches_python_reference() {
    let csv_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(CSV_REL_PATH);
    let Some(rows) = load_reference_csv(&csv_path) else {
        panic!(
            "VGCH H1: reference CSV not found at {} — regenerate via \
             `uv run scripts/validate/vgch_beta_l_heavy.py`",
            csv_path.display()
        );
    };
    assert!(!rows.is_empty(), "reference CSV empty");

    // Cache PPs per element to avoid re-parsing.
    let mut element_order: Vec<String> = Vec::new();
    for r in &rows {
        if !element_order.contains(&r.element) {
            element_order.push(r.element.clone());
        }
    }
    let pps: std::collections::HashMap<String, PseudopotentialData> = element_order
        .iter()
        .map(|e| (e.clone(), load_pp(e)))
        .collect();

    // Per-element running max |Δ|.
    let mut per_element_max: std::collections::HashMap<String, f64> =
        element_order.iter().map(|e| (e.clone(), 0.0_f64)).collect();

    let mut worst: Option<(String, usize, i32, f64, f64, f64, f64)> = None;
    let mut worst_abs_diff: f64 = 0.0;

    let mut checked = 0_usize;

    for row in &rows {
        let pp = pps.get(&row.element).expect("PP cache");
        assert!(
            row.projector_index < pp.n_projectors(),
            "{}: projector_index {} out of range ({} projectors)",
            row.element,
            row.projector_index,
            pp.n_projectors()
        );
        let proj = &pp.beta_projectors[row.projector_index];
        assert_eq!(
            proj.l, row.l,
            "{}: projector {} l mismatch (UPF {}, CSV {})",
            row.element, row.projector_index, proj.l, row.l
        );

        // Convert Rust Å^{3/2} result to Bohr^{3/2} for comparison.
        let f_ang = f_l_of_q_rust(&pp.r_grid, &pp.rab, &proj.values, row.l, row.q_per_ang);
        let f_bohr = f_ang / BOHR_TO_ANG.powf(1.5);

        // Primary comparison in Bohr (QE-native); also cross-check the Å
        // column as a sanity on unit conversion.
        let diff_bohr = f_bohr - row.f_bohr_3halves;
        let diff_ang = f_ang - row.f_ang_3halves;

        let e = per_element_max.get_mut(&row.element).unwrap();
        *e = e.max(diff_bohr.abs());

        if diff_bohr.abs() > worst_abs_diff {
            worst_abs_diff = diff_bohr.abs();
            worst = Some((
                row.element.clone(),
                row.projector_index,
                row.l,
                row.q_bohr_inv,
                row.f_bohr_3halves,
                f_bohr,
                diff_bohr,
            ));
        }

        // Sanity: Å and Bohr columns must be consistent under the
        // conversion F_Å = F_Bohr · BOHR_TO_ANG^{3/2}, independent of the
        // comparison against pwdft-rs. This is a cross-check of the
        // Python reference internal consistency.
        let bohr_from_ang = row.f_ang_3halves / BOHR_TO_ANG.powf(1.5);
        let unit_consistency = (bohr_from_ang - row.f_bohr_3halves).abs();
        assert!(
            unit_consistency < 1e-10,
            "{}: CSV Å/Bohr columns inconsistent ({:.2e})",
            row.element, unit_consistency
        );

        // Å-side cross-check: diff_ang / BOHR^{3/2} should equal diff_bohr.
        let _ = diff_ang;

        checked += 1;
    }

    eprintln!(
        "\n===== VGCH H1 β_l(q) cross-check: {} rows across {} elements =====",
        checked, element_order.len()
    );
    eprintln!(
        "{:>6}  {:>12}",
        "elem", "max |Δ| Bohr^{3/2}"
    );
    eprintln!("{:>6}  {:>12}", "----", "---------------");
    for e in &element_order {
        eprintln!("{:>6}  {:>12.3e}", e, per_element_max[e]);
    }
    if let Some((e, i, l, q, py, rust, diff)) = &worst {
        eprintln!(
            "\nworst: {e} proj={i} l={l} q={q:.3} Bohr⁻¹: \
             py={py:.6e}, rust={rust:.6e}, Δ={diff:+.3e} Bohr^{{3/2}}"
        );
    }

    // Assert: every row within tolerance. A single bad row is enough to
    // red-flag the hypothesis.
    for row in &rows {
        let pp = pps.get(&row.element).unwrap();
        let proj = &pp.beta_projectors[row.projector_index];
        let f_ang = f_l_of_q_rust(&pp.r_grid, &pp.rab, &proj.values, row.l, row.q_per_ang);
        let f_bohr = f_ang / BOHR_TO_ANG.powf(1.5);
        let diff = (f_bohr - row.f_bohr_3halves).abs();
        assert!(
            diff < TOL_BOHR_3_HALVES,
            "{} proj={} l={} q={:.3} Bohr⁻¹: py={:.6e}, rust={:.6e}, |Δ|={:.3e} > tol {:.1e}",
            row.element,
            row.projector_index,
            row.l,
            row.q_bohr_inv,
            row.f_bohr_3halves,
            f_bohr,
            diff,
            TOL_BOHR_3_HALVES
        );
    }
}
