//! VGCMP Phase 3 — cross-check pwdft-rs D_ij against an independent Python
//! reference for Si (ONCVPSP LDA).
//!
//! This test consumes `scripts/validate/dij_si_reference.csv`, generated by
//! `scripts/validate/dij_reference.py`, which parses the `<PP_DIJ>` XML
//! block of `pseudopotentials/nc/lda/Si.upf` manually and writes the 6×6
//! matrix in Rydberg atomic units (the UPF v2 native unit for D_ij).
//!
//! The reference is in Ry. pwdft-rs's `PseudopotentialData::dij` is stored
//! in internal units (eV) — the parser at `src/pseudopotential/upf.rs:77-78`
//! multiplies by `RY_TO_EV` on load. We invert that conversion here and
//! require element-wise agreement to < 1e-12 eV absolute.
//!
//! Si's UPF has 6 projectors (l = 0, 0, 1, 1, 2, 2). QE's ONCVPSP
//! diagonalizes each l-block, and for this particular PP the full 6×6
//! matrix is strictly diagonal — so the test also verifies all off-diagonal
//! entries are exactly zero.
//!
//! If the CSV is missing (e.g. running in an environment without Python),
//! the test prints a skip message and passes. The CSV is committed as a
//! generated artifact so CI runs do not depend on Python at test time.

use std::fs;
use std::path::PathBuf;

use pwdft_rs::{
    consts::RY_TO_EV,
    pseudopotential::{PseudopotentialData, load},
};

const CSV_REL_PATH: &str = "scripts/validate/dij_si_reference.csv";
const UPF_REL_PATH: &str = "pseudopotentials/nc/lda/Si.upf";

/// Tolerance: < 1e-12 eV absolute. D_ij is a plain Ry→eV multiplication —
/// agreement should be bit-exact modulo float representation round-off.
const TOL_EV: f64 = 1.0e-12;

/// One row of the reference CSV.
struct RefRow {
    i: usize,
    j: usize,
    dij_ry: f64,
}

fn load_reference_csv(path: &PathBuf) -> Option<Vec<RefRow>> {
    let content = fs::read_to_string(path).ok()?;
    let mut rows = Vec::new();
    for (line_no, line) in content.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line_no == 0 {
            // Skip header + blank lines.
            continue;
        }
        let fields: Vec<&str> = line.split(',').collect();
        if fields.len() != 3 {
            panic!("malformed CSV row at line {}: {line:?}", line_no + 1);
        }
        let i: usize = fields[0].trim().parse().unwrap();
        let j: usize = fields[1].trim().parse().unwrap();
        let dij_ry: f64 = fields[2].trim().parse().unwrap();
        rows.push(RefRow { i, j, dij_ry });
    }
    Some(rows)
}

fn load_si_pp() -> PseudopotentialData {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(UPF_REL_PATH);
    load(&path).expect("failed to parse Si.upf")
}

#[test]
fn vgcmp_phase3_dij_matches_python_reference() {
    let csv_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(CSV_REL_PATH);
    let Some(rows) = load_reference_csv(&csv_path) else {
        eprintln!(
            "VGCMP: reference CSV not found at {} — skipping cross-check.\n\
             (Run `uv run scripts/validate/dij_reference.py` to regenerate.)",
            csv_path.display()
        );
        return;
    };
    assert!(!rows.is_empty(), "reference CSV contains no data rows");

    let pp = load_si_pp();
    let n_proj = pp.n_projectors();
    assert_eq!(
        rows.len(),
        n_proj * n_proj,
        "CSV row count ({}) != n_proj² ({})",
        rows.len(),
        n_proj * n_proj,
    );

    // Per-element comparison; build a grid so the test always prints the
    // full 6×6 table (eV internal, eV reference) and its worst-case delta.
    let mut max_abs_diff_ev: f64 = 0.0;
    let mut max_abs_diff_ry: f64 = 0.0;
    let mut worst: Option<(usize, usize, f64, f64, f64)> = None;

    // Build a full n_proj × n_proj grid of diffs so we can print it.
    let mut rust_ry = vec![vec![0.0_f64; n_proj]; n_proj];
    let mut ref_ry = vec![vec![0.0_f64; n_proj]; n_proj];

    for row in &rows {
        assert!(
            row.i < n_proj && row.j < n_proj,
            "CSV (i={}, j={}) out of range for n_proj={n_proj}",
            row.i,
            row.j,
        );

        // pwdft-rs stores D_ij in eV, row-major. Convert to Ry for comparison.
        let flat_idx = row.i * n_proj + row.j;
        let d_ev = pp.dij[flat_idx];
        let d_ry = d_ev / RY_TO_EV;
        let diff_ev = d_ev - row.dij_ry * RY_TO_EV;
        let diff_ry = d_ry - row.dij_ry;

        rust_ry[row.i][row.j] = d_ry;
        ref_ry[row.i][row.j] = row.dij_ry;

        if diff_ev.abs() > max_abs_diff_ev {
            max_abs_diff_ev = diff_ev.abs();
            max_abs_diff_ry = diff_ry.abs();
            worst = Some((row.i, row.j, row.dij_ry, d_ry, diff_ry));
        }
    }

    // Projector angular momenta (used only for pretty-printing).
    let l_per_proj: Vec<i32> = pp.beta_projectors.iter().map(|b| b.l).collect();

    eprintln!("\nVGCMP Phase 3 — Si D_ij cross-check (tol = {TOL_EV:.2e} eV abs):");
    eprintln!("n_proj = {n_proj}, l_per_proj = {l_per_proj:?}");

    // Header row with column labels.
    let mut hdr = String::from("          ");
    for (j, l) in l_per_proj.iter().enumerate() {
        hdr.push_str(&format!("   j={j} (l={l})     "));
    }
    eprintln!("Rust (Ry):");
    eprintln!("{hdr}");
    for (i, row_vals) in rust_ry.iter().enumerate() {
        let mut line = format!("i={i} (l={}) ", l_per_proj[i]);
        for &val in row_vals {
            line.push_str(&format!("{val:+14.6e} "));
        }
        eprintln!("{line}");
    }

    eprintln!("\nPython (Ry):");
    eprintln!("{hdr}");
    for (i, row_vals) in ref_ry.iter().enumerate() {
        let mut line = format!("i={i} (l={}) ", l_per_proj[i]);
        for &val in row_vals {
            line.push_str(&format!("{val:+14.6e} "));
        }
        eprintln!("{line}");
    }

    eprintln!("\nmax |Δ| = {max_abs_diff_ry:.3e} Ry  ({max_abs_diff_ev:.3e} eV)");

    if max_abs_diff_ev >= TOL_EV {
        let (i, j, py, rust, diff) = worst.unwrap();
        panic!(
            "D_ij disagrees with Python reference beyond tolerance.\n\
             Worst element: (i={i}, j={j})\n\
             Python = {py:+.16e} Ry, Rust = {rust:+.16e} Ry, Δ = {diff:+.3e} Ry\n\
             max |Δ| = {max_abs_diff_ry:.3e} Ry ({max_abs_diff_ev:.3e} eV), tol = {TOL_EV:.3e} eV"
        );
    }
}
