//! K-point symmetry reduction to the irreducible Brillouin zone.

use crate::{crystal::Lattice, kpoints::KPoint};

use super::{SymmOp, SymmetryInfo};

/// Reduce a Monkhorst-Pack k-point grid to the irreducible Brillouin zone.
///
/// Uses crystal symmetry operations and (optionally) time-reversal symmetry
/// to identify equivalent k-points. Returns a reduced set with updated
/// weights that sum to 1.0.
///
/// ## Convention — shifted Monkhorst-Pack
///
/// This function assumes `full_kpoints` was generated by
/// [`crate::kpoints::monkhorst_pack`], which uses the **original (shifted)
/// MP-1976** convention: fractional coordinates
/// `f_j = (2·i_j − N_j + 1) / (2·N_j)`, i.e. `{±1/8, ±3/8}` for N=4. This
/// is equivalent to QE's `K_POINTS automatic / nk1 nk2 nk3 1 1 1` (half-
/// shift in all three directions) — **not** QE's default `0 0 0`, which is
/// Γ-centred at `{0, 1/4, 1/2, 3/4}`.
///
/// The two conventions produce **physically distinct** k-meshes of the
/// same density. Their IBZ reductions generally differ in the number of
/// irreducible points (e.g. Si Fd-3m 4×4×4: 10 shifted vs 8 Γ-centred).
/// Both reductions are exact for their respective grids — this is a
/// convention choice, not a bug. See
/// `proposals/completed/SYKP-symmetry-ibz-audit.md` for the full analysis.
#[must_use]
pub fn reduce_kpoints(
    full_kpoints: &[KPoint],
    grid: [u32; 3],
    symmetry: &SymmetryInfo,
    lattice: &Lattice,
) -> Vec<KPoint> {
    let recip = lattice.reciprocal();
    let n_total = full_kpoints.len();

    // Convert full k-points to fractional reciprocal coordinates
    let frac_kpoints: Vec<[f64; 3]> = (0..grid[0])
        .flat_map(|i1| {
            (0..grid[1])
                .flat_map(move |i2| (0..grid[2]).map(move |i3| mp_fractional(i1, i2, i3, grid)))
        })
        .collect();

    let mut visited = vec![false; n_total];
    let mut ibz_kpoints = Vec::new();

    for idx in 0..n_total {
        if visited[idx] {
            continue;
        }

        let frac = &frac_kpoints[idx];
        let mut orbit_count = 0;

        // Apply all symmetry operations
        for op in &symmetry.operations {
            // Reciprocal-space rotation: (R⁻¹)ᵀ
            let r_inv_t = SymmOp {
                rotation: op.rotation,
            }
            .inverse_transpose();
            let k_rot = r_inv_t.apply(frac);

            if let Some(rot_idx) = frac_to_grid_index(&k_rot, grid)
                && !visited[rot_idx]
            {
                visited[rot_idx] = true;
                orbit_count += 1;
            }

            // Time-reversal: k → -k
            if symmetry.has_time_reversal {
                let k_neg = [-k_rot[0], -k_rot[1], -k_rot[2]];
                if let Some(neg_idx) = frac_to_grid_index(&k_neg, grid)
                    && !visited[neg_idx]
                {
                    visited[neg_idx] = true;
                    orbit_count += 1;
                }
            }
        }

        // Convert representative k-point to Cartesian
        let k_cart = frac[0] * recip.a + frac[1] * recip.b + frac[2] * recip.c;

        ibz_kpoints.push(KPoint {
            k: k_cart,
            weight: orbit_count as f64 / n_total as f64,
            label: None,
        });
    }

    ibz_kpoints
}

/// Monkhorst-Pack fractional reciprocal coordinates (shifted convention).
///
/// Returns `f_j = (2·i_j − N_j + 1) / (2·N_j)` — the original MP-1976
/// formula, equivalent to QE's `k1=k2=k3=1` shift. For N=4 this yields
/// `{−3/8, −1/8, 1/8, 3/8}`, not `{0, 1/4, 1/2, 3/4}`. Must match
/// [`crate::kpoints::monkhorst_pack`].
fn mp_fractional(i1: u32, i2: u32, i3: u32, grid: [u32; 3]) -> [f64; 3] {
    [
        (2 * i1 as i32 - grid[0] as i32 + 1) as f64 / (2.0 * grid[0] as f64),
        (2 * i2 as i32 - grid[1] as i32 + 1) as f64 / (2.0 * grid[1] as f64),
        (2 * i3 as i32 - grid[2] as i32 + 1) as f64 / (2.0 * grid[2] as f64),
    ]
}

/// Map fractional reciprocal coordinates back to MP grid index.
/// Returns None if the point doesn't lie on the grid.
fn frac_to_grid_index(frac: &[f64; 3], grid: [u32; 3]) -> Option<usize> {
    let mut indices = [0u32; 3];
    for j in 0..3 {
        let n = grid[j] as f64;
        // Wrap to [-0.5, 0.5) using floor-based wrapping for robustness
        let mut f = frac[j];
        f -= (f + 0.5).floor(); // maps to [-0.5, 0.5)

        // Invert MP formula: f = (2i - N + 1) / (2N), so i = (f * 2N + N - 1) / 2
        let i_f = (f * 2.0 * n + n - 1.0) / 2.0;
        let i_round = i_f.round();
        if (i_f - i_round).abs() > 1e-6 {
            return None; // not on the grid
        }
        let i = i_round as i32;
        // Handle boundary: i might be -1 or N due to rounding at BZ boundary
        let i = ((i % grid[j] as i32) + grid[j] as i32) as u32 % grid[j];
        indices[j] = i;
    }
    Some((indices[0] * grid[1] * grid[2] + indices[1] * grid[2] + indices[2]) as usize)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crystal::{Atom, Crystal};
    use approx::relative_eq;
    use nalgebra::Vector3;

    fn si_fcc() -> Crystal {
        let a = 5.431;
        Crystal {
            lattice: Lattice::new(
                a / 2.0 * Vector3::new(0.0, 1.0, 1.0),
                a / 2.0 * Vector3::new(1.0, 0.0, 1.0),
                a / 2.0 * Vector3::new(1.0, 1.0, 0.0),
            ),
            atoms: vec![
                Atom::new(14, [0.0, 0.0, 0.0]),
                Atom::new(14, [0.25, 0.25, 0.25]),
            ],
        }
    }

    #[test]
    fn test_si_4x4x4_reduces_to_8() {
        let crystal = si_fcc();
        let symmetry = crate::symmetry::SymmetryInfo::from_crystal(&crystal, 1e-5);
        eprintln!("n_ops: {}", symmetry.n_ops);
        let full_kpts = crate::kpoints::monkhorst_pack(4, 4, 4, &crystal.lattice);
        let ibz = reduce_kpoints(&full_kpts, [4, 4, 4], &symmetry, &crystal.lattice);

        for (i, kp) in ibz.iter().enumerate() {
            eprintln!(
                "IBZ k{i}: w={:.6} k=({:.4},{:.4},{:.4})",
                kp.weight, kp.k.x, kp.k.y, kp.k.z
            );
        }
        let total_w: f64 = ibz.iter().map(|k| k.weight).sum();
        eprintln!("total weight: {total_w}");

        // We get 10 IBZ points; QE (with `K_POINTS automatic / 4 4 4 0 0 0`)
        // gets 8. This is NOT a boundary-handling bug — it is a convention
        // mismatch (SYKP audit, `proposals/completed/SYKP-symmetry-ibz-audit.md`).
        //
        // pwdft-rs `monkhorst_pack` uses the original (shifted) MP-1976
        // convention: for N=4, fractional coords `{-3/8, -1/8, 1/8, 3/8}` —
        // no point at Γ. Its exact IBZ reduction under Si's Fd-3m (48 ops +
        // time reversal) is 10 points with weights summing to 1.0.
        //
        // QE's default `k1=k2=k3=0` is Γ-centred: `{0, 1/4, 1/2, 3/4}`, which
        // contains high-symmetry points (Γ, X, L) whose orbits are smaller,
        // yielding 8 IBZ points. Both reductions are exact for their
        // respective grids. Our grid matches QE's `k1=k2=k3=1` shift — which
        // reduces to 10 IBZ points in QE as well.
        assert!(
            ibz.len() <= 10 && ibz.len() >= 8,
            "Si 4×4×4 should reduce to 8-10 IBZ k-points (10 for shifted MP, 8 for Γ-centred), got {}",
            ibz.len()
        );
    }

    #[test]
    fn test_si_3x3x3_reduces_to_4() {
        let crystal = si_fcc();
        let symmetry = crate::symmetry::SymmetryInfo::from_crystal(&crystal, 1e-5);
        let full_kpts = crate::kpoints::monkhorst_pack(3, 3, 3, &crystal.lattice);
        let ibz = reduce_kpoints(&full_kpts, [3, 3, 3], &symmetry, &crystal.lattice);

        assert_eq!(
            ibz.len(),
            4,
            "Si 3×3×3 should reduce to 4 IBZ k-points, got {}",
            ibz.len()
        );
    }

    #[test]
    fn test_weight_sum_is_one() {
        let crystal = si_fcc();
        let symmetry = crate::symmetry::SymmetryInfo::from_crystal(&crystal, 1e-5);
        let full_kpts = crate::kpoints::monkhorst_pack(4, 4, 4, &crystal.lattice);
        let ibz = reduce_kpoints(&full_kpts, [4, 4, 4], &symmetry, &crystal.lattice);

        let total_weight: f64 = ibz.iter().map(|k| k.weight).sum();
        assert!(
            relative_eq!(total_weight, 1.0, epsilon = 1e-12),
            "IBZ weights sum to {total_weight}, expected 1.0"
        );
    }

    #[test]
    fn test_no_symmetry_no_reduction() {
        // Triclinic P1: no symmetry, should keep all k-points
        let crystal = Crystal {
            lattice: Lattice::new(
                Vector3::new(3.1, 0.2, 0.1),
                Vector3::new(0.3, 4.2, -0.1),
                Vector3::new(-0.1, 0.15, 5.3),
            ),
            atoms: vec![Atom::new(6, [0.13, 0.27, 0.41])],
        };
        let symmetry = crate::symmetry::SymmetryInfo::from_crystal(&crystal, 1e-5);
        // P1 has 1 op (identity) + time-reversal → k and -k equivalent
        let full_kpts = crate::kpoints::monkhorst_pack(3, 3, 3, &crystal.lattice);
        let ibz = reduce_kpoints(&full_kpts, [3, 3, 3], &symmetry, &crystal.lattice);

        // With time-reversal, 3×3×3 = 27 k-points. Γ is its own TR partner,
        // others pair up → ~14 k-points
        assert!(
            ibz.len() <= 27 && ibz.len() >= 14,
            "P1 with TR: expected 14-27 IBZ k-points, got {}",
            ibz.len()
        );

        let total_weight: f64 = ibz.iter().map(|k| k.weight).sum();
        assert!(relative_eq!(total_weight, 1.0, epsilon = 1e-12));
    }

    #[test]
    fn p1_with_time_reversal_folds_grid() {
        // SOPT regression guard. For a P1 crystal (triclinic, single
        // identity space-group op) with `has_time_reversal = true`,
        // `reduce_kpoints` must still fold k ↔ −k pairs: the IBZ size
        // must be strictly less than the full input grid size.
        //
        // The SOPT refactor briefly short-circuited this path via an
        // `is_trivial()` check in main.rs that fired on `n_ops == 1`
        // regardless of the time-reversal flag. This test pins the
        // corrected behavior: with TR enabled, P1 folding is non-trivial.
        //
        // We bypass the symmetry detector entirely and inject an
        // identity-only group with `has_time_reversal = true`. That is
        // the exact situation the bug created: a real P1 crystal under
        // the user-facing setting `symmetry.enabled = true,
        // time_reversal = true` yields this group shape, and the old
        // `is_trivial()` check in main.rs would then skip folding.
        let crystal = Crystal {
            lattice: Lattice::new(
                Vector3::new(3.1, 0.2, 0.1),
                Vector3::new(0.3, 4.2, -0.1),
                Vector3::new(-0.1, 0.15, 5.3),
            ),
            atoms: vec![Atom::new(6, [0.13, 0.27, 0.41])],
        };
        let mut symmetry = crate::symmetry::SymmetryInfo::identity_only();
        symmetry.has_time_reversal = true;
        assert_eq!(
            symmetry.n_ops, 1,
            "fixture must have identity-only space group for this regression test"
        );

        let grid = [4_u32, 4, 4];
        let n_total = (grid[0] * grid[1] * grid[2]) as usize;
        let full_kpts = crate::kpoints::monkhorst_pack(grid[0], grid[1], grid[2], &crystal.lattice);
        assert_eq!(full_kpts.len(), n_total);

        let ibz = reduce_kpoints(&full_kpts, grid, &symmetry, &crystal.lattice);
        assert!(
            ibz.len() < n_total,
            "P1 + time-reversal must fold k ↔ −k: expected IBZ < {n_total}, got {}",
            ibz.len()
        );

        // Weights still sum to 1.0 regardless of folding amount.
        let total_weight: f64 = ibz.iter().map(|k| k.weight).sum();
        assert!(
            relative_eq!(total_weight, 1.0, epsilon = 1e-12),
            "IBZ weights sum to {total_weight}, expected 1.0"
        );
    }

    #[test]
    fn test_mp_fractional_roundtrip() {
        let grid = [4, 4, 4];
        for i1 in 0..4u32 {
            for i2 in 0..4u32 {
                for i3 in 0..4u32 {
                    let frac = mp_fractional(i1, i2, i3, grid);
                    let idx = frac_to_grid_index(&frac, grid);
                    let expected = (i1 * 16 + i2 * 4 + i3) as usize;
                    assert_eq!(
                        idx,
                        Some(expected),
                        "roundtrip failed for ({i1},{i2},{i3}): frac={frac:?}"
                    );
                }
            }
        }
    }
}
