//! K-point symmetry reduction to the irreducible Brillouin zone.

use crate::{
    crystal::Lattice,
    kpoints::{KGridShift, KPoint},
};

use super::{SymmOp, SymmetryInfo};

/// Reduce a Monkhorst-Pack k-point grid to the irreducible Brillouin zone.
///
/// Uses crystal symmetry operations and (optionally) time-reversal symmetry
/// to identify equivalent k-points. Returns a reduced set with updated
/// weights that sum to 1.0.
///
/// ## Convention
///
/// `shift` **must** match the convention under which `full_kpoints` was
/// generated by [`crate::kpoints::monkhorst_pack`]; the reducer uses it to
/// invert the grid-index mapping and find orbit partners. Passing the wrong
/// shift silently mis-indexes Γ-centered grids (or MP-1976 grids) and
/// produces incorrect weights. The function generator and reducer must
/// agree.
///
/// - `KGridShift::GammaCentered` (QE default): fractional coords
///   `{0, 1/N, 2/N, …, (N−1)/N}`. Si Fd-3m 4×4×4 reduces to **8** IBZ
///   points (matches QE).
/// - `KGridShift::MP1976` (QE `k1=k2=k3=1`): fractional coords
///   `{±1/(2N), ±3/(2N), …}`. Si Fd-3m 4×4×4 reduces to **10** IBZ points.
///
/// Both reductions are exact for their respective grids — this is a
/// convention choice, not a bug. See
/// `proposals/completed/SYKP-symmetry-ibz-audit.md` and
/// `proposals/MPSH-mp-shift-alignment.md` for the background.
#[must_use]
pub fn reduce_kpoints(
    full_kpoints: &[KPoint],
    grid: [u32; 3],
    shift: KGridShift,
    symmetry: &SymmetryInfo,
    lattice: &Lattice,
) -> Vec<KPoint> {
    let recip = lattice.reciprocal();
    let n_total = full_kpoints.len();

    // Convert full k-points to fractional reciprocal coordinates
    let frac_kpoints: Vec<[f64; 3]> = (0..grid[0])
        .flat_map(|i1| {
            (0..grid[1]).flat_map(move |i2| {
                (0..grid[2]).map(move |i3| mp_fractional(i1, i2, i3, grid, shift))
            })
        })
        .collect();

    let mut visited = vec![false; n_total];
    let mut ibz_kpoints = Vec::new();

    for idx in 0..n_total {
        if visited[idx] {
            continue;
        }

        let frac = &frac_kpoints[idx];
        let mut orbit_count = 0;

        // Apply all symmetry operations
        for op in &symmetry.operations {
            // Reciprocal-space rotation: (R⁻¹)ᵀ
            let r_inv_t = SymmOp {
                rotation: op.rotation,
            }
            .inverse_transpose();
            let k_rot = r_inv_t.apply(frac);

            if let Some(rot_idx) = frac_to_grid_index(&k_rot, grid, shift)
                && !visited[rot_idx]
            {
                visited[rot_idx] = true;
                orbit_count += 1;
            }

            // Time-reversal: k → -k
            if symmetry.has_time_reversal {
                let k_neg = [-k_rot[0], -k_rot[1], -k_rot[2]];
                if let Some(neg_idx) = frac_to_grid_index(&k_neg, grid, shift)
                    && !visited[neg_idx]
                {
                    visited[neg_idx] = true;
                    orbit_count += 1;
                }
            }
        }

        // Convert representative k-point to Cartesian
        let k_cart = frac[0] * recip.a + frac[1] * recip.b + frac[2] * recip.c;

        ibz_kpoints.push(KPoint {
            k: k_cart,
            weight: orbit_count as f64 / n_total as f64,
            label: None,
        });
    }

    ibz_kpoints
}

/// Monkhorst-Pack fractional reciprocal coordinates for the given shift.
///
/// Delegates to [`crate::kpoints::mp_fractional_coord`] so this module and
/// the grid generator share a single formula. Must match
/// [`crate::kpoints::monkhorst_pack`].
fn mp_fractional(i1: u32, i2: u32, i3: u32, grid: [u32; 3], shift: KGridShift) -> [f64; 3] {
    crate::kpoints::mp_fractional_coord(i1, i2, i3, grid, shift)
}

/// Map fractional reciprocal coordinates back to MP grid index.
/// Returns None if the point doesn't lie on the grid under the given shift.
///
/// Inverts `f_α = i_α/N_α + k_α/(2·N_α)` for `i_α ∈ [0, N_α)`:
/// `i_α = f_α · N_α − k_α/2` (modulo integer lattice). We wrap `f_α` into
/// `[0, 1)` first so negative fractionals (from rotated k-vectors) are
/// handled uniformly.
fn frac_to_grid_index(frac: &[f64; 3], grid: [u32; 3], shift: KGridShift) -> Option<usize> {
    let flags = shift.axis_flags();
    let mut indices = [0u32; 3];
    for j in 0..3 {
        let n = f64::from(grid[j]);
        let k_shift = f64::from(flags[j]);
        // Wrap into [0, 1).
        let f = frac[j] - frac[j].floor();

        // Invert: i_f = f * N - k/2.
        let i_f = f * n - 0.5 * k_shift;
        let i_round = i_f.round();
        if (i_f - i_round).abs() > 1e-6 {
            return None; // not on the grid
        }
        #[allow(
            clippy::cast_possible_truncation,
            reason = "i_round comes from inverting the MP formula with N <= O(100); bounded by N and fits in i32"
        )]
        let i = i_round as i32;
        // Wrap i into [0, N): i might be -1 or N from edge rounding.
        #[allow(
            clippy::cast_possible_wrap,
            clippy::cast_sign_loss,
            reason = "grid[j] < i32::MAX trivially; (i % d) + d is mathematically >= 1 so `as u32` loses no sign"
        )]
        let i = ((i % grid[j] as i32) + grid[j] as i32) as u32 % grid[j];
        indices[j] = i;
    }
    Some((indices[0] * grid[1] * grid[2] + indices[1] * grid[2] + indices[2]) as usize)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crystal::{Atom, Crystal};
    use approx::relative_eq;
    use nalgebra::Vector3;

    fn si_fcc() -> Crystal {
        let a = 5.431;
        Crystal {
            lattice: Lattice::new(
                a / 2.0 * Vector3::new(0.0, 1.0, 1.0),
                a / 2.0 * Vector3::new(1.0, 0.0, 1.0),
                a / 2.0 * Vector3::new(1.0, 1.0, 0.0),
            ),
            atoms: vec![
                Atom::new(14, [0.0, 0.0, 0.0]),
                Atom::new(14, [0.25, 0.25, 0.25]),
            ],
        }
    }

    #[test]
    fn test_si_4x4x4_gamma_centered_reduces_to_8() {
        // Γ-centered grid (QE default `4 4 4 0 0 0`): {0, 1/4, 1/2, 3/4}
        // includes Γ, X, L. Exact Fd-3m (48 ops) reduction → 8 IBZ points,
        // matching QE.
        let crystal = si_fcc();
        let symmetry = crate::symmetry::SymmetryInfo::from_crystal(&crystal, 1e-5);
        let full_kpts =
            crate::kpoints::monkhorst_pack(4, 4, 4, KGridShift::GammaCentered, &crystal.lattice);
        let ibz = reduce_kpoints(
            &full_kpts,
            [4, 4, 4],
            KGridShift::GammaCentered,
            &symmetry,
            &crystal.lattice,
        );

        let total_w: f64 = ibz.iter().map(|k| k.weight).sum();
        assert_eq!(
            ibz.len(),
            8,
            "Γ-centered Si 4×4×4 should reduce to exactly 8 IBZ k-points, got {}",
            ibz.len()
        );
        assert!(
            relative_eq!(total_w, 1.0, epsilon = 1e-12),
            "Γ-centered IBZ weights sum to {total_w}, expected 1.0"
        );
    }

    #[test]
    fn test_si_4x4x4_mp1976_reduces_to_10() {
        // MP-1976 shifted grid (QE `4 4 4 1 1 1`): {±1/8, ±3/8} — no Γ,
        // no BZ-boundary high-symmetry points. Fd-3m reduction → 10 IBZ
        // points. Legacy behavior preserved for calculations that want
        // the original Monkhorst-Pack 1976 recipe.
        let crystal = si_fcc();
        let symmetry = crate::symmetry::SymmetryInfo::from_crystal(&crystal, 1e-5);
        let full_kpts =
            crate::kpoints::monkhorst_pack(4, 4, 4, KGridShift::MP1976, &crystal.lattice);
        let ibz = reduce_kpoints(
            &full_kpts,
            [4, 4, 4],
            KGridShift::MP1976,
            &symmetry,
            &crystal.lattice,
        );

        assert_eq!(
            ibz.len(),
            10,
            "MP-1976 Si 4×4×4 should reduce to exactly 10 IBZ k-points, got {}",
            ibz.len()
        );
    }

    #[test]
    fn test_si_3x3x3_reduces_to_4() {
        // For odd N, Γ-centered and MP-1976 produce the same mesh modulo a
        // cyclic permutation — IBZ size is identical under either shift.
        let crystal = si_fcc();
        let symmetry = crate::symmetry::SymmetryInfo::from_crystal(&crystal, 1e-5);
        let full_kpts =
            crate::kpoints::monkhorst_pack(3, 3, 3, KGridShift::GammaCentered, &crystal.lattice);
        let ibz = reduce_kpoints(
            &full_kpts,
            [3, 3, 3],
            KGridShift::GammaCentered,
            &symmetry,
            &crystal.lattice,
        );

        assert_eq!(
            ibz.len(),
            4,
            "Si 3×3×3 should reduce to 4 IBZ k-points, got {}",
            ibz.len()
        );
    }

    #[test]
    fn test_weight_sum_is_one() {
        let crystal = si_fcc();
        let symmetry = crate::symmetry::SymmetryInfo::from_crystal(&crystal, 1e-5);
        let full_kpts =
            crate::kpoints::monkhorst_pack(4, 4, 4, KGridShift::GammaCentered, &crystal.lattice);
        let ibz = reduce_kpoints(
            &full_kpts,
            [4, 4, 4],
            KGridShift::GammaCentered,
            &symmetry,
            &crystal.lattice,
        );

        let total_weight: f64 = ibz.iter().map(|k| k.weight).sum();
        assert!(
            relative_eq!(total_weight, 1.0, epsilon = 1e-12),
            "IBZ weights sum to {total_weight}, expected 1.0"
        );
    }

    #[test]
    fn test_no_symmetry_no_reduction() {
        // Triclinic P1: no symmetry, should keep all k-points
        let crystal = Crystal {
            lattice: Lattice::new(
                Vector3::new(3.1, 0.2, 0.1),
                Vector3::new(0.3, 4.2, -0.1),
                Vector3::new(-0.1, 0.15, 5.3),
            ),
            atoms: vec![Atom::new(6, [0.13, 0.27, 0.41])],
        };
        let symmetry = crate::symmetry::SymmetryInfo::from_crystal(&crystal, 1e-5);
        // P1 has 1 op (identity) + time-reversal → k and -k equivalent
        let full_kpts =
            crate::kpoints::monkhorst_pack(3, 3, 3, KGridShift::GammaCentered, &crystal.lattice);
        let ibz = reduce_kpoints(
            &full_kpts,
            [3, 3, 3],
            KGridShift::GammaCentered,
            &symmetry,
            &crystal.lattice,
        );

        // With time-reversal, 3×3×3 = 27 k-points. Γ is its own TR partner,
        // others pair up → ~14 k-points
        assert!(
            ibz.len() <= 27 && ibz.len() >= 14,
            "P1 with TR: expected 14-27 IBZ k-points, got {}",
            ibz.len()
        );

        let total_weight: f64 = ibz.iter().map(|k| k.weight).sum();
        assert!(relative_eq!(total_weight, 1.0, epsilon = 1e-12));
    }

    #[test]
    fn p1_with_time_reversal_folds_grid() {
        // SOPT regression guard. For a P1 crystal (triclinic, single
        // identity space-group op) with `has_time_reversal = true`,
        // `reduce_kpoints` must still fold k ↔ −k pairs: the IBZ size
        // must be strictly less than the full input grid size.
        //
        // The SOPT refactor briefly short-circuited this path via an
        // `is_trivial()` check in main.rs that fired on `n_ops == 1`
        // regardless of the time-reversal flag. This test pins the
        // corrected behavior: with TR enabled, P1 folding is non-trivial.
        //
        // We bypass the symmetry detector entirely and inject an
        // identity-only group with `has_time_reversal = true`. That is
        // the exact situation the bug created: a real P1 crystal under
        // the user-facing setting `symmetry.enabled = true,
        // time_reversal = true` yields this group shape, and the old
        // `is_trivial()` check in main.rs would then skip folding.
        let crystal = Crystal {
            lattice: Lattice::new(
                Vector3::new(3.1, 0.2, 0.1),
                Vector3::new(0.3, 4.2, -0.1),
                Vector3::new(-0.1, 0.15, 5.3),
            ),
            atoms: vec![Atom::new(6, [0.13, 0.27, 0.41])],
        };
        let mut symmetry = crate::symmetry::SymmetryInfo::identity_only();
        symmetry.has_time_reversal = true;
        assert_eq!(
            symmetry.n_ops, 1,
            "fixture must have identity-only space group for this regression test"
        );

        let grid = [4_u32, 4, 4];
        let n_total = (grid[0] * grid[1] * grid[2]) as usize;
        let full_kpts = crate::kpoints::monkhorst_pack(
            grid[0],
            grid[1],
            grid[2],
            KGridShift::GammaCentered,
            &crystal.lattice,
        );
        assert_eq!(full_kpts.len(), n_total);

        let ibz = reduce_kpoints(
            &full_kpts,
            grid,
            KGridShift::GammaCentered,
            &symmetry,
            &crystal.lattice,
        );
        assert!(
            ibz.len() < n_total,
            "P1 + time-reversal must fold k ↔ −k: expected IBZ < {n_total}, got {}",
            ibz.len()
        );

        // Weights still sum to 1.0 regardless of folding amount.
        let total_weight: f64 = ibz.iter().map(|k| k.weight).sum();
        assert!(
            relative_eq!(total_weight, 1.0, epsilon = 1e-12),
            "IBZ weights sum to {total_weight}, expected 1.0"
        );
    }

    #[test]
    fn test_mp_fractional_roundtrip_gamma_centered() {
        let grid = [4, 4, 4];
        for i1 in 0..4u32 {
            for i2 in 0..4u32 {
                for i3 in 0..4u32 {
                    let frac = mp_fractional(i1, i2, i3, grid, KGridShift::GammaCentered);
                    let idx = frac_to_grid_index(&frac, grid, KGridShift::GammaCentered);
                    let expected = (i1 * 16 + i2 * 4 + i3) as usize;
                    assert_eq!(
                        idx,
                        Some(expected),
                        "Γ-centered roundtrip failed for ({i1},{i2},{i3}): frac={frac:?}"
                    );
                }
            }
        }
    }

    #[test]
    fn test_mp_fractional_roundtrip_mp1976() {
        let grid = [4, 4, 4];
        for i1 in 0..4u32 {
            for i2 in 0..4u32 {
                for i3 in 0..4u32 {
                    let frac = mp_fractional(i1, i2, i3, grid, KGridShift::MP1976);
                    let idx = frac_to_grid_index(&frac, grid, KGridShift::MP1976);
                    let expected = (i1 * 16 + i2 * 4 + i3) as usize;
                    assert_eq!(
                        idx,
                        Some(expected),
                        "MP-1976 roundtrip failed for ({i1},{i2},{i3}): frac={frac:?}"
                    );
                }
            }
        }
    }

    #[test]
    fn test_mp_fractional_roundtrip_custom() {
        let grid = [4, 4, 4];
        for shift in [
            KGridShift::Custom([1, 0, 0]),
            KGridShift::Custom([0, 1, 0]),
            KGridShift::Custom([1, 0, 1]),
        ] {
            for i1 in 0..4u32 {
                for i2 in 0..4u32 {
                    for i3 in 0..4u32 {
                        let frac = mp_fractional(i1, i2, i3, grid, shift);
                        let idx = frac_to_grid_index(&frac, grid, shift);
                        let expected = (i1 * 16 + i2 * 4 + i3) as usize;
                        assert_eq!(
                            idx,
                            Some(expected),
                            "Custom-shift roundtrip failed for ({i1},{i2},{i3}) shift={shift:?}: frac={frac:?}"
                        );
                    }
                }
            }
        }
    }
}
